export function validProductionEnvironment(overrides = {}) {
  return {
    NODE_ENV: "production",
    STAGED_MODE: "false",
    XYGO_DEPLOY_ENVIRONMENT: "production",
    XYGO_RELEASE: "0123456789abcdef",
    XYGO_AUTH_MODE: "oidc",
    XYGO_API_REPOSITORY_MODE: "postgres",
    XYGO_API_PG_URL: "postgresql://xygo:database-password@db.production.xygoaec.com/xygo?sslmode=verify-full",
    XYGO_PG_POOL_MAX: "10",
    XYGO_PG_IDLE_TIMEOUT_MS: "30000",
    XYGO_PG_CONNECTION_TIMEOUT_MS: "5000",
    XYGO_OIDC_PROVIDER: "other-managed-oidc",
    XYGO_OIDC_ISSUER: "https://idp.production.xygoaec.com/",
    XYGO_OIDC_AUDIENCE: "https://api.production.xygoaec.com",
    XYGO_OIDC_JWKS_URI: "https://idp.production.xygoaec.com/.well-known/jwks.json",
    XYGO_OIDC_ALLOWED_ALGORITHMS: "RS256",
    XYGO_OIDC_CLOCK_TOLERANCE_SEC: "60",
    XYGO_AUDIT_SIGNING_KEY: "audit-signing-key-material-with-at-least-32-characters",
    XYGO_WEB_APP_URL: "https://app.production.xygoaec.com",
    XYGO_WEB_API_BASE_URL: "https://api.production.xygoaec.com",
    XYGO_WEB_OIDC_CLIENT_ID: "xygo-public-web-client",
    XYGO_WEB_OIDC_AUTHORIZATION_ENDPOINT: "https://idp.production.xygoaec.com/authorize",
    XYGO_WEB_OIDC_TOKEN_ENDPOINT: "https://idp.production.xygoaec.com/oauth/token",
    XYGO_WEB_OIDC_END_SESSION_ENDPOINT: "https://idp.production.xygoaec.com/logout",
    XYGO_WEB_OIDC_SCOPES: "openid profile email",
    XYGO_WEB_MONITORING_ENDPOINT: "https://browser-monitoring.production.xygoaec.com/events",
    XYGO_EMAIL_TRANSPORT: "resend",
    XYGO_EMAIL_FROM: "Xygo Notifications <notifications@updates.xygoaec.com>",
    XYGO_EMAIL_REPLY_TO: "support@xygoaec.com",
    XYGO_EMAIL_RESEND_API_URL: "https://api.resend.com",
    XYGO_EMAIL_RESEND_API_KEY: "re_0123456789abcdef0123456789abcdef",
    XYGO_EMAIL_WEBHOOK_SECRET: `whsec_${Buffer.from("0123456789abcdef0123456789abcdef").toString("base64")}`,
    XYGO_EMAIL_REQUEST_TIMEOUT_MS: "10000",
    XYGO_STORAGE_DRIVER: "s3",
    XYGO_STORAGE_BUCKET: "xygo-production-uploads",
    XYGO_STORAGE_REGION: "us-east-1",
    XYGO_STORAGE_ENDPOINT: "https://storage.production.xygoaec.com",
    XYGO_STORAGE_ACCESS_KEY_ID: "xygo-storage-access-key",
    XYGO_STORAGE_SECRET_ACCESS_KEY: "storage-secret-at-least-16-characters",
    XYGO_STORAGE_FORCE_PATH_STYLE: "false",
    XYGO_STORAGE_PUBLIC_ACCESS: "blocked",
    XYGO_STORAGE_SERVER_SIDE_ENCRYPTION: "AES256",
    XYGO_STORAGE_MAX_FILE_BYTES: "26214400",
    XYGO_STORAGE_ALLOWED_MIME_TYPES: "application/pdf,image/jpeg,image/png,image/webp,text/plain",
    XYGO_STORAGE_SIGNED_URL_TTL_SEC: "300",
    XYGO_STORAGE_RETENTION_DAYS: "365",
    XYGO_OUTBOX_BACKEND: "postgres",
    XYGO_WORKER_INTERVAL_MS: "1000",
    XYGO_WORKER_MAX_ATTEMPTS: "5",
    XYGO_WORKER_BASE_BACKOFF_MS: "1000",
    XYGO_WORKER_MAX_BACKOFF_MS: "900000",
    XYGO_WORKER_CONCURRENCY: "4",
    XYGO_WORKER_STALE_AFTER_MS: "60000",
    XYGO_WORKER_SHUTDOWN_TIMEOUT_MS: "30000",
    XYGO_WORKER_MAX_DEAD_JOBS: "0",
    XYGO_MONITORING_ENABLED: "true",
    XYGO_MONITORING_OTLP_ENDPOINT: "https://telemetry.production.xygoaec.com/v1",
    XYGO_MONITORING_AUTH_TOKEN: "monitoring-token-at-least-16-characters",
    XYGO_ALERT_OUTBOX_BACKLOG_MAX: "1000",
    XYGO_ALERT_OUTBOX_OLDEST_PENDING_SEC: "900",
    XYGO_ALERT_EMAIL_FAILED_MAX: "0",
    XYGO_ALERT_EMAIL_STALE_SEC: "900",
    XYGO_ALERT_DATABASE_LATENCY_MS: "2000",
    XYGO_ALERT_WORKER_HEARTBEAT_SEC: "120",
    ...overrides
  };
}
