export function validProductionEnvironment(overrides = {}) {
  return {
    NODE_ENV: "production",
    STAGED_MODE: "false",
    XYGO_DEPLOY_ENVIRONMENT: "production",
    XYGO_RELEASE: "0123456789abcdef",
    XYGO_AUTH_MODE: "oidc",
    XYGO_API_REPOSITORY_MODE: "postgres",
    XYGO_API_PG_URL: "postgresql://xygo:database-password@db.xygo.invalid/xygo?sslmode=verify-full",
    XYGO_OIDC_PROVIDER: "other-managed-oidc",
    XYGO_OIDC_ISSUER: "https://idp.xygo.invalid/",
    XYGO_OIDC_AUDIENCE: "https://api.xygo.invalid",
    XYGO_OIDC_JWKS_URI: "https://idp.xygo.invalid/.well-known/jwks.json",
    XYGO_OIDC_ALLOWED_ALGORITHMS: "RS256",
    XYGO_OIDC_CLOCK_TOLERANCE_SEC: "60",
    XYGO_AUDIT_SIGNING_KEY: "audit-signing-key-material-with-at-least-32-characters",
    XYGO_WEB_APP_URL: "https://app.xygo.invalid",
    XYGO_WEB_API_BASE_URL: "https://api.xygo.invalid",
    XYGO_WEB_OIDC_CLIENT_ID: "xygo-public-web-client",
    XYGO_WEB_OIDC_AUTHORIZATION_ENDPOINT: "https://idp.xygo.invalid/authorize",
    XYGO_WEB_OIDC_TOKEN_ENDPOINT: "https://idp.xygo.invalid/oauth/token",
    XYGO_WEB_OIDC_END_SESSION_ENDPOINT: "https://idp.xygo.invalid/logout",
    XYGO_WEB_OIDC_SCOPES: "openid profile email",
    XYGO_WEB_MONITORING_ENDPOINT: "https://browser-monitoring.xygo.invalid/events",
    XYGO_EMAIL_TRANSPORT: "smtp",
    XYGO_EMAIL_FROM: "notifications@xygo.invalid",
    XYGO_SMTP_HOST: "smtp.xygo.invalid",
    XYGO_SMTP_PORT: "465",
    XYGO_SMTP_USERNAME: "xygo-notifications",
    XYGO_SMTP_PASSWORD: "smtp-password-at-least-16-characters",
    XYGO_STORAGE_DRIVER: "s3",
    XYGO_STORAGE_BUCKET: "xygo-production-uploads",
    XYGO_STORAGE_REGION: "us-east-1",
    XYGO_STORAGE_ENDPOINT: "https://storage.xygo.invalid",
    XYGO_STORAGE_ACCESS_KEY_ID: "xygo-storage-access-key",
    XYGO_STORAGE_SECRET_ACCESS_KEY: "storage-secret-at-least-16-characters",
    XYGO_OUTBOX_BACKEND: "postgres",
    XYGO_WORKER_INTERVAL_MS: "1000",
    XYGO_WORKER_MAX_ATTEMPTS: "5",
    XYGO_WORKER_BASE_BACKOFF_MS: "1000",
    XYGO_WORKER_CONCURRENCY: "4",
    XYGO_MONITORING_OTLP_ENDPOINT: "https://telemetry.xygo.invalid/v1",
    XYGO_MONITORING_AUTH_TOKEN: "monitoring-token-at-least-16-characters",
    ...overrides
  };
}
