// PostgreSQL adapter for the authenticated audit. The caller supplies the same
// application encryption codec used for other sensitive client records.
export function createPostgresAuditRepository({pool,encryptJson,decryptJson,lookupHash}){
  if(!pool?.query||!encryptJson||!decryptJson)throw new Error("Postgres audit repository requires pool and encryption codec.");
  const decode=row=>row?decryptJson(row.payload_ciphertext??row.projection_ciphertext??row.content_ciphertext??row.value_ciphertext??row.state_ciphertext??row.response_ciphertext):null;
  return {
    async ensureUser(principal){
      if(!principal?.userId||!principal?.identitySubject||!principal?.identityProvider||!principal?.emailVerified||!principal?.verifiedEmail||!lookupHash)throw Object.assign(new Error("A verified email identity is required."),{status:401});
      const emailHash=lookupHash(principal.verifiedEmail);const now=new Date().toISOString();
      await pool.query("BEGIN");try{
        await pool.query("INSERT INTO client_users(id,email_lookup_hash,email_ciphertext,name_ciphertext,email_verified_at,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,'active',$5,$5) ON CONFLICT(id) DO UPDATE SET email_lookup_hash=EXCLUDED.email_lookup_hash,email_ciphertext=EXCLUDED.email_ciphertext,name_ciphertext=EXCLUDED.name_ciphertext,email_verified_at=EXCLUDED.email_verified_at,status='active',updated_at=EXCLUDED.updated_at",[principal.userId,emailHash,encryptJson(principal.verifiedEmail),encryptJson(principal.displayName??principal.verifiedEmail),now]);
        await pool.query("INSERT INTO client_identities(id,user_id,provider,provider_subject,last_login_at) VALUES($1,$2,'enterprise_sso',$3,$4) ON CONFLICT(provider,provider_subject) DO UPDATE SET user_id=EXCLUDED.user_id,last_login_at=EXCLUDED.last_login_at",[`oidc:${principal.userId}`,principal.userId,`${principal.identityProvider}|${principal.identitySubject}`,now]);
        await pool.query("COMMIT");return {id:principal.userId};
      }catch(error){await pool.query("ROLLBACK");throw error}
    },
    async createWorkspace(record){await pool.query("BEGIN");try{await pool.query("INSERT INTO tenants(id,name) VALUES($1,$2)",[record.id,record.displayName]);await pool.query("INSERT INTO client_workspaces(id,legal_name,display_name,status) VALUES($1,$2,$2,$3)",[record.id,record.displayName,record.status]);await pool.query("COMMIT");return record}catch(error){await pool.query("ROLLBACK");throw error}},
    async getWorkspace(workspaceId){const {rows}=await pool.query("SELECT id,display_name AS \"displayName\",status,created_at AS \"createdAt\" FROM client_workspaces WHERE id=$1",[workspaceId]);return rows[0]??null},
    async saveMembership(record){await pool.query("INSERT INTO client_workspace_members(workspace_id,user_id,role,status) VALUES($1,$2,$3,$4) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=EXCLUDED.role,status=EXCLUDED.status,revoked_at=NULL",[record.workspaceId,record.userId,record.role,record.status]);return record},
    async getMembership(workspaceId,userId){const {rows}=await pool.query("SELECT workspace_id AS \"workspaceId\",user_id AS \"userId\",role,status FROM client_workspace_members WHERE workspace_id=$1 AND user_id=$2 AND status='active'",[workspaceId,userId]);return rows[0]??null},
    async listMembershipsForUser(userId){const {rows}=await pool.query("SELECT workspace_id AS \"workspaceId\",user_id AS \"userId\",role,status FROM client_workspace_members WHERE user_id=$1 AND status='active' ORDER BY created_at",[userId]);return rows},
    async revokeMembership(workspaceId,userId,at){const {rows}=await pool.query("UPDATE client_workspace_members SET status='revoked',revoked_at=$3 WHERE workspace_id=$1 AND user_id=$2 RETURNING workspace_id AS \"workspaceId\",user_id AS \"userId\",role,status,revoked_at AS \"revokedAt\"",[workspaceId,userId,at]);return rows[0]??null},
    async saveInvitation(record){await pool.query("INSERT INTO workspace_invitations(id,workspace_id,email_lookup_hash,role,status,created_by,expires_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[record.id,record.workspaceId,record.emailLookupHash,record.role,record.status,record.createdBy,record.expiresAt??new Date(Date.now()+604800000),record.createdAt]);return record},
    async getInvitation(invitationId){const {rows}=await pool.query("SELECT id,workspace_id AS \"workspaceId\",email_lookup_hash AS \"emailLookupHash\",role,status,created_by AS \"createdBy\",expires_at AS \"expiresAt\" FROM workspace_invitations WHERE id=$1",[invitationId]);return rows[0]??null},
    async acceptInvitation(invitationId,userId,at){const {rows}=await pool.query("UPDATE workspace_invitations SET status='accepted',accepted_by=$2,accepted_at=$3 WHERE id=$1 AND status='pending' RETURNING *",[invitationId,userId,at]);return rows[0]??null},
    async saveConversation(record){await pool.query("INSERT INTO audit_conversations(id,workspace_id,created_by,title,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,status=EXCLUDED.status,updated_at=EXCLUDED.updated_at",[record.id,record.workspaceId,record.createdBy,record.title,record.status,record.createdAt,record.updatedAt]);return record},
    async getConversation(workspaceId,conversationId){const {rows}=await pool.query("SELECT id,workspace_id AS \"workspaceId\",created_by AS \"createdBy\",title,status,created_at AS \"createdAt\",updated_at AS \"updatedAt\" FROM audit_conversations WHERE workspace_id=$1 AND id=$2",[workspaceId,conversationId]);return rows[0]??null},
    async listConversations(workspaceId){const {rows}=await pool.query("SELECT id,workspace_id AS \"workspaceId\",created_by AS \"createdBy\",title,status FROM audit_conversations WHERE workspace_id=$1 ORDER BY updated_at DESC",[workspaceId]);return rows},
    async appendMessage(record){await pool.query("INSERT INTO audit_messages(id,workspace_id,conversation_id,role,content_ciphertext,structured_ciphertext,model_version,prompt_version,validation_status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[record.id,record.workspaceId,record.conversationId,record.role,encryptJson(record.content),record.structured?encryptJson(record.structured):null,record.modelVersion??null,record.promptVersion??null,"valid",record.createdAt]);return record},
    async listMessages(workspaceId,conversationId){const {rows}=await pool.query("SELECT id,workspace_id AS \"workspaceId\",conversation_id AS \"conversationId\",role,content_ciphertext,structured_ciphertext,created_at AS \"createdAt\" FROM audit_messages WHERE workspace_id=$1 AND conversation_id=$2 ORDER BY created_at,id",[workspaceId,conversationId]);return rows.map(row=>({...row,content:decode(row),structured:row.structured_ciphertext?decryptJson(row.structured_ciphertext):undefined}))},
    async saveAuditState(record){await pool.query("INSERT INTO audit_states(conversation_id,workspace_id,current_stage,completed_stages,readiness,evidence_coverage,confidence,free_result_eligible,state_ciphertext,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(conversation_id) DO UPDATE SET current_stage=EXCLUDED.current_stage,completed_stages=EXCLUDED.completed_stages,readiness=EXCLUDED.readiness,evidence_coverage=EXCLUDED.evidence_coverage,confidence=EXCLUDED.confidence,free_result_eligible=EXCLUDED.free_result_eligible,state_ciphertext=EXCLUDED.state_ciphertext,updated_at=EXCLUDED.updated_at",[record.conversationId,record.workspaceId,record.currentStage,record.completedStages,record.readiness,record.evidenceCoverage,record.confidence,record.freeResultEligible,encryptJson(record),record.updatedAt]);return record},
    async getAuditState(workspaceId,conversationId){const {rows}=await pool.query("SELECT state_ciphertext FROM audit_states WHERE workspace_id=$1 AND conversation_id=$2",[workspaceId,conversationId]);return rows[0]?decode(rows[0]):null},
    async saveEvidence(record){await pool.query("INSERT INTO audit_evidence_refs(id,workspace_id,conversation_id,source_type,source_record_hash,label_ciphertext,owner_user_id,confidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[record.id,record.workspaceId,record.conversationId,record.sourceType,record.sourceRecordHash??null,encryptJson(record.label),record.ownerUserId??null,record.confidence??null]);return record},
    async listEvidence(workspaceId,conversationId){const {rows}=await pool.query("SELECT id,workspace_id AS \"workspaceId\",conversation_id AS \"conversationId\",source_type AS \"sourceType\",label_ciphertext,confidence FROM audit_evidence_refs WHERE workspace_id=$1 AND conversation_id=$2 ORDER BY created_at",[workspaceId,conversationId]);return rows.map(row=>({...row,label:decryptJson(row.label_ciphertext)}))},
    async saveCanvasSnapshot(record){await pool.query("INSERT INTO audit_canvas_snapshots(workspace_id,conversation_id,projection_ciphertext,created_at) VALUES($1,$2,$3,$4)",[record.workspaceId,record.conversationId,encryptJson(record.projection),record.createdAt]);return record},
    async getCanvasSnapshot(workspaceId,conversationId){const {rows}=await pool.query("SELECT workspace_id AS \"workspaceId\",conversation_id AS \"conversationId\",projection_ciphertext,created_at AS \"createdAt\" FROM audit_canvas_snapshots WHERE workspace_id=$1 AND conversation_id=$2 ORDER BY created_at DESC,id DESC LIMIT 1",[workspaceId,conversationId]);return rows[0]?{...rows[0],projection:decode(rows[0])}:null},
    async saveToolInvocation(record){await pool.query("INSERT INTO audit_tool_invocations(id,workspace_id,conversation_id,requested_by,tool_name,arguments_ciphertext,idempotency_key,approval_status,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[record.id,record.workspaceId,record.conversationId??null,record.userId,record.tool,encryptJson(record.arguments??{}),record.idempotencyKey,record.approvalStatus??"not_required",record.status,record.createdAt]);return record},
    async getIdempotent(key){const [workspaceId,conversationId,...rest]=key.split(":");const {rows}=await pool.query("SELECT response_ciphertext FROM audit_request_idempotency WHERE workspace_id=$1 AND conversation_id=$2 AND idempotency_key=$3 AND expires_at>now()",[workspaceId,conversationId,rest.join(":")]);return rows[0]?decode(rows[0]):null},
    async saveIdempotent(key,value){const [workspaceId,conversationId,...rest]=key.split(":");await pool.query("INSERT INTO audit_request_idempotency(workspace_id,conversation_id,idempotency_key,response_ciphertext,expires_at) VALUES($1,$2,$3,$4,now()+interval '24 hours') ON CONFLICT(workspace_id,conversation_id,idempotency_key) DO NOTHING",[workspaceId,conversationId,rest.join(":"),encryptJson(value)]);return value}
  };
}
